# Generated by Django 5.1.1 on 2024-10-06 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
