# Generated by Django 5.1.1 on 2024-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='family',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='family',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='family',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RenameField(
            model_name='bucketlist',
            old_name='family',
            new_name='family_id',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='bucket_content',
        ),
        migrations.RemoveField(
            model_name='bucketlist',
            name='id',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='bucket_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
